Both: Client Server
Server: CaesarCipherServer.class
Client: Client.class

Client.class: Client.java
	javac -deprecation Client.java

CaesarCipherServer.class: CaesarCipherServer.java
	javac -deprecation CaesarCipherServer.java

clean:
	rm -f *.class *~ *#
